name: Continuous integration (PRs)
on: pull_request
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:playwright

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run ViTest tests
        run: npm run test:vitest:ci
      - run: npm run check
